apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 80
  selector:
    app: elasticsearch
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: frontend
    spec:
      containers:
      - image: elasticsearch:7.13.1
        name: elasticsearch
        env:
        - name: ELASTICSEARCH_DB_HOST
          value: elasticsearch-mysql
        - name: ELASTICSEARCH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: elasticsearch
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
